# Generated by Django 3.2.5 on 2021-08-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifyfigure',
            name='figure',
            field=models.FloatField(),
        ),
    ]
