# Generated by Django 3.2.5 on 2021-08-09 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_goal_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_alter_certifyfigure_figure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='certify_image/')),
                ('text', models.TextField(blank=True, null=True)),
                ('figure', models.FloatField(blank=True, null=True)),
                ('achievement', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifies', to='main.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='certifyimage',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='certifyimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='certifytext',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='certifytext',
            name='user',
        ),
        migrations.DeleteModel(
            name='CertifyFigure',
        ),
        migrations.DeleteModel(
            name='CertifyImage',
        ),
        migrations.DeleteModel(
            name='CertifyText',
        ),
    ]
