# Generated by Django 3.2.5 on 2021-08-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210809_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certify',
            name='achievement',
            field=models.BooleanField(default=True),
        ),
    ]
